version: '3.7'
services:
  database:
    image: postgres:10.12 # use latest official postgres version
    restart: always
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: vking34
        POSTGRES_DB: users
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports: 
        - 5432:5432
    expose:
        - 5432

volumes:
  database-data: # named volumes can be managed easier using docker-compose